### ISSUE TITLE
npm install itself fails in windows

### ISSUE THREAD

**Issue by julianfrank** [jazzyarchitects/fasttext-node#3]
```bash
npm i fasttext-node

> fasttext-node@1.1.6 postinstall E:\<removed>\node_modules\fasttext-node
> ./install.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
[            ......] - postinstall: info lifecycle fasttext-node@1.1.6~postinstall: Failed to exec postinstall script
```

Windows 10
Node v8.9.0
Npm 5.5.1

**Comment by jazzyarchitects** [comment]
Hi @julianfrank 
The build scripts have not yet been written for windows. Since I don't have a windows machine I couldn't test this. Will roll out the script soon. 

It will be helpful if you can help with this.

Or you can hear for any updates on https://gitter.im/fasttext-node/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

Cheers

**Comment by julianfrank** [comment]
I Installed from bash and the error changed to this 
```bash
: npm i fasttext-node --save
npm WARN babel-loader@7.1.2 requires a peer of webpack@2 || 3 but none is installed. You must install peer dependencies yourself.

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```
I'm skipping the warning about webpack...

WRT the Rror -> Looks like here the problem is the specification given for platform in the fsevents thingy... 
Not sure how to solve this however :(

**Comment by jazzyarchitects** [comment]
@julianfrank The module still doesn't support windows. May I suggest using docker containers.?

**Comment by julianfrank** [comment]
I guess I'll have to giveup on windows :(
